# Generated by Django 5.1.7 on 2025-03-19 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=20, unique=True, verbose_name='ISIN')),
                ('nominal', models.FloatField(verbose_name='Valeur nominale')),
                ('taux_facial', models.FloatField(verbose_name='Taux facial')),
                ('date_valeur', models.DateField(verbose_name='Date de valeur')),
                ('maturite', models.FloatField(verbose_name='Maturité (en années)')),
                ('prix_pondere', models.FloatField(verbose_name='Prix pondéré')),
                ('type_obligation', models.CharField(choices=[('OAT', 'Obligation Assimilable du Trésor'), ('BAT', 'Bon du Trésor')], max_length=3, verbose_name="Type d'Obligation")),
            ],
        ),
        migrations.CreateModel(
            name='PaysUEMOA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeTitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_titre', models.CharField(choices=[('OAT', 'Obligation Assimilable du Trésor'), ('BAT', 'Bon Assimilable du Trésor')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Amortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Date d'amortissement")),
                ('montant', models.FloatField(verbose_name='Montant')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortissements', to='Applicaion.obligation')),
            ],
        ),
        migrations.AddField(
            model_name='obligation',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Applicaion.paysuemoa', verbose_name='Pays'),
        ),
    ]
